### ISSUE TITLE
Not working on macOS.

### ISSUE THREAD

**Issue by raguay** [pomdtr/popcorn#2]
Hi, I followed the instructions (and did the `npm i` in the extension directory before building) and loaded the extension. But, the extension says:

Unchecked runtime.lastError: Access to the specified native messaging host is forbidden.
Context
Unknown
Stack Trace
:0 (anonymous function)

I'm not sure how to give access to it. This should be included in the instructions.

**Comment by pomdtr** [comment]
Sorry about this. I fixed the installation instructions can you retry ?

Please reopen the issue if you encounter any issue.

**Comment by raguay** [comment]
Hi, I recloned the repo and redid the installation process, but I'm still getting the same error and the terminal windows opens with nothing in it but a blinking cursor. My Chrome version is:  Version 113.0.5672.126 (Official Build) (arm64)

**Comment by raguay** [comment]
Not sure how to get to a log for it. Is it in the extension directory? The
service worker just gives an error:  Unchecked runtime.lastError: Native
host has exited.

**Comment by pomdtr** [comment]
How I found the error, my username is just hardcoded inside the setup script. Can you try again ?

**Comment by raguay** [comment]
Same error. I wiped it from my system, redownloaded and followed the instructions. It still gives the same errors.

**Comment by pomdtr** [comment]
Can you give me the content of the ~/.local/bin/popcorn.sh file ?

**Comment by pomdtr** [comment]
Ok, can you run a last git pull ? I fixed the issue

**Comment by raguay** [comment]
changing bash to zsh and it now works for me. The .bashrc isn't up to date.

**Comment by pomdtr** [comment]
This commit should fix the issue: https://github.com/pomdtr/popcorn/commit/09200c2426c94700ab8686316492a1a626dbc00d. 

I was not providing the full path to the binary

**Comment by raguay** [comment]
Yes. It works now. Thanks.

**Comment by raguay** [comment]
It's really neat. I can't believe it handles run nvim just fine.

**Comment by pomdtr** [comment]
It is just the start. I want to build a real integrated terminal for chromium browsers:

Here are some planned features:
- omnibox integrations
- terminal inside of tabs
- support for multiple browsers / profiles

**Comment by pomdtr** [comment]
Yeah arc is a weird one, since they don't really document how to integrate with them. But I like it too :)

**Comment by raguay** [comment]
It is a highly modified Chromium application. But, every iteration gets more and more away from it. But, I still install most Chrome extension that I use and they work fine (other than popcorn now 😢 ).

**Comment by pomdtr** [comment]
I think it is probably possible, I just need to find out how to wire the cli to their browser. Stay tuned!
